apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: bar
  name: bar-script
data:
  app.py: |
          #!/usr/local/bin/python
          from flask import Flask
          import os

          app = Flask(__name__)

          @app.route('/version')
          def version():
              return os.getenv("Version")

          if __name__ == '__main__':
            app.run()

